name: Weld App tests

on: [push]

jobs:
  weld-app-tests:
    name: Run tests for Weld App
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.11"
      POETRY_VERSION: "1.8.2"

    steps:
    - uses: actions/checkout@v4

    - name: install python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: install poetry
      uses: snok/install-poetry@v1
      with:
        version: ${{ env.POETRY_VERSION }}

    - name: Install dependencies
      run: |
        poetry install

    - name: Run tests
      run: poetry run pytest